### ISSUE TITLE
refactor provision_phone_number

### ISSUE THREAD

**Issue by GregBaugues** [TwilioDevEd/anonymous-communications-rails#6]
[Here](https://github.com/TwilioDevEd/anonymous-communications-rails/blob/master/app/models/reservation.rb#L63). 

 For the sake of single responsibility, and because it'll make the narrative easier, I'd suggest creating a ```lib/twilio_module.rb``` where you store your Twilio logic. Then you can either include it in an object, or call it verbosely using something like ```TwilioModule::twilio_client```. (I do the first method because it's prettier, but it's not always obvious where these methods are magically coming from). 

Your twilio module might look like: 

```ruby
module TwilioModule

  def twilio_client
    Twilio::REST::Client.new ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN']
  end

  def avilable_numbers_in_area_code(area_code)
    twilio_client.account.available_phone_numbers.get('US').local.list(:area_code => area_code)
  end

  def available_numbers_anywhere
    twilio_client.account.available_phone_numbers.get('US').local.list
  end

  def available_number(area_code)
    numbers = available_numbers_in_area_code(area_code)
    numbers.present? ? numbers.first : available_numbers_anywhere.first
  end

  def buy_number(number)
    client.account.incoming_phone_numbers.create(:phone_number => number)
  end

  def buy_an_available_number(area_code)
    number = available_number(area_code)
    buy_number(number) #returns a twilio_number object
  end

  def update_application_sids(phone_number)
    phone_number.update(
      :voice_application_sid => ENV['ANONYMOUS_APPLICATION_SID'],
      :sms_application_sid => ENV['ANONYMOUS_APPLICATION_SID']
    )
  end

end
```

You will need to create a file at ```config/initializers/modules.rb``` that simply says: 

```ruby
require File.join(Rails.root, "lib/twilio_module.rb")
```

This tells Rails to load the module when it starts up, which it won't do otherwise. 

With all this reusable logic in place, your provision_phone_number becomes: 

```ruby 
include TwilioModule
def provision_phone_number
  begin
    anon_number = buy_an_available_number(self.host.area_code)
    update_application_sids(anon_number)
    self.update(phone_number: anon_number.phone_number)
  rescue Exception => e
    puts "ERROR: #{e.message}"
  end
end
```

I haven't tested any of this code, so I'm sure it has errors. I'm also not sure that including a module is the best practice way of doing this so you might want to run it past Phil. But I suspect that extracting the Twilio logic into macro-like methods will make it easier to explain what's going on.

**Comment by jarodreyes** [comment]
This is awesome @GregBaugues. @philnash Any thoughts on including a module like this? I originally decided against this (concern, module, etc) because I didn't want to muck up the narrative with "why some Twilio logic is in a module and some is in models/controllers". After all if I create a Twilio module, shouldn't it also handle sending/routing calls and sms traffic? Would love thoughts on this.

**Comment by philnash** [comment]
I have absolutely done something like this in an old project to wrap up the usage of an API. I would probably do so with a `class` rather than a module though. Then you can write more sensible methods for things `available_numbers_in_area_code` that are nicer to use and more intention revealing within the rest of the code. You can then expose existing behaviour of the client by forwarding methods onto the cached instance variable.

It basically becomes your own custom API wrapper for your own uses and avoids polluting the already busy set of methods an `ActiveRecord::Base` or `ActionController::Base` based object has. It's probably easier to test too.

```ruby
require 'twilio-ruby'
require 'forwardable'
 
class TwilioClient
  def initialize
    @client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_AUTH_TOKEN'])
  end

  def buy_an_available_number(area_code)
    number = available_number(area_code)
    buy_number(number) #returns a twilio_number object
  end

  def update_application_sids(phone_number)
    phone_number.update(
      :voice_application_sid => ENV['ANONYMOUS_APPLICATION_SID'],
      :sms_application_sid => ENV['ANONYMOUS_APPLICATION_SID']
    )
  end

  # you could delegate methods on the @client object
  extend Forwardable
  def_delegators :@client, :messages, :calls
  
  # or just define more, and easier, helper methods
  # def send_message(from, to, body)
  #   @client.messages.create(from: from, to: to, body: body)
  # end

  private

  def avilable_numbers_in_area_code(area_code)
    @client.available_phone_numbers.get('US').local.list(:area_code => area_code)
  end

  def available_numbers_anywhere
    @client.available_phone_numbers.get('US').local.list
  end

  def available_number(area_code)
    numbers = available_numbers_in_area_code(area_code)
    numbers.present? ? numbers.first : available_numbers_anywhere.first
  end
end
```

Then you'd use this class like:

```ruby
def provision_phone_number
  twilio = TwilioClient.new
  begin
    anon_number = twilio.buy_an_available_number(self.host.area_code)
    twilio.update_application_sids(anon_number)
    self.update(phone_number: anon_number.phone_number)
  rescue StandardError => e
    puts "ERROR: #{e.message}"
  end
end
```

What do you think?

**Comment by jarodreyes** [comment]
@philnash @GregBaugues thanks for the feedback. Much appreciated!
